spring.application.name=Qrcode

# ✅ Railway MySQL direct URL (NO variables)
spring.datasource.url=jdbc:mysql://switchyard.proxy.rlwy.net:42785/railway
spring.datasource.username=root
spring.datasource.password=UmNKhuRzvwsAFKKiAJbZcTbEMGdpyPDA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ✅ VERY IMPORTANT (Railway port)
server.port=${PORT:8080}
app.base-url=${APP_URL:http://localhost:8080}