spring.application.name=Qrcode


spring.datasource.url=mysql://root:UmNKhuRzvwsAFKKiAJbZcTbEMGdpyPDA@switchyard.proxy.rlwy.net:42785/railway
spring.datasource.username=root
spring.datasource.password=UmNKhuRzvwsAFKKiAJbZcTbEMGdpyPDA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true